### ISSUE TITLE
GLASS3 not processing multiple pick files

### ISSUE THREAD

**Issue by wyeck-usgs** [usgs/neic-glass3#19]
* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**
GLASS 3 is not running through all json pick files in run on Northern California data. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Running our two-week NC test case only returns short period of data. It appears that the glass3 is shutting down too soon. 

* **What is the expected behavior?**
It should process all pick files.

**Comment by jpatton-USGS** [comment]
User Error
